# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys-A7-100T-Master.xdc

# IP: ip/xadc_ip_1/xadc_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_ip || ORIG_REF_NAME==xadc_ip} -quiet] -quiet
