#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 15 21:26:53 AWST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_func_synth -key {Post-Synthesis:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/bd_fc5c_0.protoinst" -log simulate.log"
xsim top_func_synth -key {Post-Synthesis:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/bd_fc5c_0.protoinst" -log simulate.log

