# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0 || ORIG_REF_NAME==bd_fc5c_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_0_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_0_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_0_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0_ooc_debug.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0_ooc.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0 || ORIG_REF_NAME==bd_fc5c_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_0_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_0_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_0_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0_ooc_debug.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0_ooc.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FAX/digitalnoNacrt/vaje7/vaje7.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
